### ISSUE TITLE
Smol typo in blaseball-reference.com swagger

### ISSUE THREAD

**Issue by ch4zm** [Society-for-Internet-Blaseball-Research/datablase#13]
Hello, I noticed a smol typo in the blaseball-reference.com swagger spec, under the `events/` endpoint:

<img width="689" alt="Screen Shot 2020-09-13 at 11 40 20 " src="https://user-images.githubusercontent.com/70510814/93025815-0b42c680-f5b6-11ea-99c5-a2a6d8e8b6d6.png">

Batter ID field description says "pitcher" but should say "batter"

Couldn't find the swagger yaml anywhere, so hopefully this is a good place to open this issue

**Comment by markrjamieson** [comment]
https://github.com/Society-for-Internet-Blaseball-Research/datablase/pull/14
